name: Create RadioQTama Subtitle

on:
  push:
    branches: [QuonTama]
  # schedule:
  #   - cron:  '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write
  contents: write

jobs:
  Create_RadioQTama_Subtitle:
    runs-on: windows-latest # dotnet SDK built-in

    steps:
      - uses: actions/checkout@v2
        with:
          ref: QuonTama

      # If no changes have been made, the program will exit with error code 80, and terminate CI.
      - name: Fetch and recreate RadioQTama subtitles
        shell: cmd
        run: "call .github\\workflows\\CreateRadioQTamaSubtitles.exe"

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          branch: QuonTama
          commit_message: "Github Action: Fetch and recreate RadioQTama subtitles"
          commit_user_name: Github Action Bot # defaults to "GitHub Actions"
          commit_author: Github Action Bot <actions@github.com> # defaults to author of the commit that triggered the run

  Auto_PR:
    needs: Create_RadioQTama_Subtitle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: QuonTama

      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "QuonTama to master auto PR" --body ":robot: Automated PR from **QuonTama** to **master**" --base master --head QuonTama
